apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-rs

spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
      tier: app

  template:
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: app
          image: dolsam77/echo